//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAdministrative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbadvertising
    {
        public int idtbadvertising { get; set; }
        public string imageadvertisingpath { get; set; }
        public string urladvertising { get; set; }
    }
}
