//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAdministrative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbfacility
    {
        public int idtbfacility { get; set; }
        public string facility { get; set; }
        public string descriptionfacility { get; set; }
        public string imagefacilitypath { get; set; }
    }
}
