//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAdministrative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbhotel
    {
        public int idtbhotel { get; set; }
        public string namehotel { get; set; }
        public string basicinformation { get; set; }
        public string history { get; set; }
        public string mission { get; set; }
        public string vission { get; set; }
        public string location { get; set; }
    }
}
