//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAdministrative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbimageroom
    {
        public int idtbimageroom { get; set; }
        public string imageroompath { get; set; }
        public int room { get; set; }
    
        public virtual tbroom tbroom { get; set; }
    }
}
