//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAdministrative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbpromotion
    {
        public int idtbpromotion { get; set; }
        public string promotion { get; set; }
        public string descriptionpromotion { get; set; }
        public string imagepromotion { get; set; }
    }
}
