//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAdministrative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbreservation
    {
        public int idtbreservation { get; set; }
        public string reservationnumber { get; set; }
        public int client { get; set; }
        public int creditcard { get; set; }
        public int room { get; set; }
        public System.DateTime indate { get; set; }
        public System.DateTime outdate { get; set; }
    
        public virtual tbclient tbclient { get; set; }
        public virtual tbroom tbroom { get; set; }
    }
}
