//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAdministrative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbroomtype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbroomtype()
        {
            this.tbrooms = new HashSet<tbroom>();
        }
    
        public int idtbroomtype { get; set; }
        public string roomtype { get; set; }
        public string descriptionroom { get; set; }
        public int quantitypersons { get; set; }
        public decimal price { get; set; }
        public string imagepathroomtype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbroom> tbrooms { get; set; }
    }
}
