//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAdministrative.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbroomtype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbroomtype()
        {
            this.tbrooms = new HashSet<tbroom>();
        }
    
        public int idtbroomtype { get; set; }

        [Required(ErrorMessage = "Escriba el nombre de la habitación")]
        [StringLength(65, ErrorMessage = "El tamaño es muy grande")]
        public string roomtype { get; set; }

        [Required(ErrorMessage = "Escriba una descripción")]
        [StringLength(200, ErrorMessage = "El tamaño es muy grande")]
        public string descriptionroom { get; set; }

        [Required(ErrorMessage = "Escriba la cantidad de personas")]
        public int quantitypersons { get; set; }

        [Required(ErrorMessage = "Escriba el precio por noche")]
        public decimal price { get; set; }

        [Required(ErrorMessage = "Por favor, agregue una imagen")]
        public string imagepathroomtype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbroom> tbrooms { get; set; }
    }
}
