//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAdministrative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbuser
    {
        public int idtbuser { get; set; }
        public string nametbuser { get; set; }
        public string password { get; set; }
        public int idtbrole { get; set; }
    
        public virtual tbrole tbrole { get; set; }
    }
}
