//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAdministrative.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbuseradmin
    {
        public int idtbuseradmin { get; set; }
        public string nameuseradmin { get; set; }
        public string emailuseradmin { get; set; }
        public string passworduseradmin { get; set; }
        public string loginErrorMessage { get; set; }
    }
}
