//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModAdministrative.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aurorahotelEntities : DbContext
    {
        public aurorahotelEntities()
            : base("name=aurorahotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbadvertising> tbadvertisings { get; set; }
        public virtual DbSet<tbclient> tbclients { get; set; }
        public virtual DbSet<tbemail> tbemails { get; set; }
        public virtual DbSet<tbfacility> tbfacilities { get; set; }
        public virtual DbSet<tbhotel> tbhotels { get; set; }
        public virtual DbSet<tbimagegallery> tbimagegalleries { get; set; }
        public virtual DbSet<tbimageroom> tbimagerooms { get; set; }
        public virtual DbSet<tbphone> tbphones { get; set; }
        public virtual DbSet<tbpromotion> tbpromotions { get; set; }
        public virtual DbSet<tbreservation> tbreservations { get; set; }
        public virtual DbSet<tbroom> tbrooms { get; set; }
        public virtual DbSet<tbroomtype> tbroomtypes { get; set; }
        public virtual DbSet<tbsocialred> tbsocialreds { get; set; }
        public virtual DbSet<tbuseradmin> tbuseradmins { get; set; }
        public virtual DbSet<tbrole> tbroles { get; set; }
        public virtual DbSet<tbuser> tbusers { get; set; }
    }
}
